import type { CourseWeek, ScriptLine } from "./types";

const pt = (text: string): ScriptLine => ({ lang: "pt", text });
const fr = (text: string): ScriptLine => ({ lang: "fr", text });

/** Semana 1 — A0: cumprimentos, nome, educação, números 0–10. */
export const week01: CourseWeek = {
  week: 1,
  phase: "Fase 1 · Ouvir e sobreviver",
  level: "A0",
  title: "Bonjour — primeiro contato",
  theme: "Cumprimentos, dizer o nome, educação e números 0–10",
  goals: [
    "Cumprimentar e se despedir",
    "Dizer e perguntar o nome",
    "Usar merci, s’il vous plaît, oui, non",
    "Contar de 0 a 10 e reconhecer no áudio",
  ],
  checkpoint:
    "Fazer um diálogo de 60 segundos: Bonjour → Je m’appelle… → Ça va ? → Merci, au revoir — sem português.",
  published: true,
  days: [
    {
      id: "mon",
      label: "Segunda",
      title: "Bonjour e salut",
      focus: "Oi, tchau e como vai",
      minutes: "~25–35 min de áudio + prática",
      lessonAudio: [
        pt("Bem-vindo à semana um do francês. Hoje é segunda-feira. Vamos aprender cumprimentos."),
        pt("A primeira palavra é bonjour. Em português significa oi, ou bom dia. Use durante o dia, de forma educada."),
        fr("Bonjour."),
        pt("Repita: bonjour."),
        fr("Bonjour."),
        pt("Salut também significa oi, mas é informal, entre amigos. Pode ser oi ou tchau casual."),
        fr("Salut."),
        pt("Repita: salut."),
        fr("Salut."),
        pt("Bonsoir significa boa noite, ou boa tarde à noite. Use à noite."),
        fr("Bonsoir."),
        pt("Repita: bonsoir."),
        fr("Bonsoir."),
        pt("Au revoir significa tchau, ou até logo, de forma educada."),
        fr("Au revoir."),
        pt("Repita: au revoir."),
        fr("Au revoir."),
        pt("À bientôt significa até logo, até em breve."),
        fr("À bientôt."),
        pt("Repita: à bientôt."),
        fr("À bientôt."),
        pt("Ça va, com ponto de interrogação, significa como vai? É muito comum."),
        fr("Ça va ?"),
        pt("Repita: ça va?"),
        fr("Ça va ?"),
        pt("Ça va bien significa estou bem, ou vai bem."),
        fr("Ça va bien."),
        pt("Merci significa obrigado."),
        fr("Merci."),
        pt("Et toi significa e você, no informal. Et vous é e você, no formal ou no trabalho."),
        fr("Et toi ?"),
        fr("Et vous ?"),
        pt("Agora um diálogo completo. Ouça e depois repita mentalmente."),
        fr("Bonjour !"),
        fr("Bonjour ! Ça va ?"),
        fr("Ça va bien, merci. Et toi ?"),
        fr("Ça va. Au revoir !"),
        fr("À bientôt !"),
        pt("Em português, esse diálogo foi: oi; oi, como vai; estou bem, obrigado, e você; estou bem, tchau; até logo."),
        pt("Fim da lição de segunda. Marque o áudio como concluído e faça o quiz quando quiser."),
      ],
      vocab: [
        { fr: "bonjour", pt: "oi / bom dia (educado)" },
        { fr: "salut", pt: "oi / tchau (informal)" },
        { fr: "bonsoir", pt: "boa noite / boa tarde à noite" },
        { fr: "au revoir", pt: "tchau / até logo" },
        { fr: "à bientôt", pt: "até logo / até em breve" },
        { fr: "ça va ?", pt: "como vai?" },
        { fr: "ça va bien", pt: "estou bem / vai bem" },
        { fr: "merci", pt: "obrigado" },
        { fr: "et toi ?", pt: "e você? (informal)" },
        { fr: "et vous ?", pt: "e você? (formal)" },
      ],
      grammar: {
        title: "Tu vs vous (primeiro contato)",
        points: [
          "toi / tu = informal (amigos, família, pessoas da sua idade).",
          "vous = educado ou plural (desconhecidos, trabalho).",
          "No trabalho e com estranhos, prefira et vous e s’il vous plaît.",
          "Ça va ? funciona com os dois.",
        ],
      },
      writing: {
        title: "Escreva 4 linhas",
        prompt: "Escreva um mini diálogo no trabalho: Bonjour → Ça va ? → resposta → Au revoir.",
        example:
          "A: Bonjour !\nB: Bonjour ! Ça va ?\nA: Ça va bien, merci. Et vous ?\nB: Ça va. Au revoir !",
      },
      quiz: [
        {
          id: "w1d1-q1",
          prompt: "Cumprimento à noite:",
          options: ["Bonjour", "Bonsoir", "Merci", "Oui"],
          correctIndex: 1,
        },
        {
          id: "w1d1-q2",
          prompt: "Oi informal:",
          options: ["Au revoir", "Bonsoir", "Salut", "Et vous"],
          correctIndex: 2,
        },
        {
          id: "w1d1-q3",
          prompt: "Obrigado:",
          options: ["Merci", "Non", "Salut", "Ça va"],
          correctIndex: 0,
        },
      ],
    },
    {
      id: "tue",
      label: "Terça",
      title: "Je m’appelle…",
      focus: "Dizer e perguntar o nome",
      minutes: "~25–35 min de áudio + prática",
      lessonAudio: [
        pt("Terça-feira. Hoje você aprende a dizer o nome em francês."),
        pt("Je m’appelle significa eu me chamo. Em português: meu nome é."),
        fr("Je m’appelle Pedro."),
        pt("Isso significa: eu me chamo Pedro. Repita."),
        fr("Je m’appelle Pedro."),
        pt("Agora com outro nome. Je m’appelle Caroline."),
        fr("Je m’appelle Caroline."),
        pt("Para perguntar o nome no informal: Comment tu t’appelles? Significa como você se chama?"),
        fr("Comment tu t’appelles ?"),
        pt("Repita a pergunta."),
        fr("Comment tu t’appelles ?"),
        pt("No formal, no trabalho: Comment vous appelez-vous? Também significa como você se chama?"),
        fr("Comment vous appelez-vous ?"),
        pt("Repita."),
        fr("Comment vous appelez-vous ?"),
        pt("Enchanté, dito por homem, significa prazer em conhecer. Enchantée, dito por mulher, é a mesma ideia."),
        fr("Enchanté."),
        fr("Enchantée."),
        pt("Je suis significa eu sou. Brésilien é brasileiro, homem. Brésilienne é brasileira, mulher."),
        fr("Je suis brésilien."),
        pt("Ouça um diálogo de apresentação."),
        fr("Bonjour. Je m’appelle Pedro."),
        fr("Enchantée. Je m’appelle Marie."),
        fr("Comment tu t’appelles ?"),
        fr("Moi, je m’appelle Luc."),
        pt("Tradução: oi, eu me chamo Pedro; prazer, eu me chamo Marie; como você se chama; eu me chamo Luc."),
        pt("Fim da lição de terça. Pratique dizer: Bonjour. Je m’appelle Pedro."),
      ],
      vocab: [
        { fr: "je m’appelle…", pt: "eu me chamo… / meu nome é…" },
        { fr: "comment tu t’appelles ?", pt: "como você se chama? (informal)" },
        { fr: "comment vous appelez-vous ?", pt: "como você se chama? (formal)" },
        { fr: "enchanté / enchantée", pt: "prazer em conhecer" },
        { fr: "moi", pt: "eu" },
        { fr: "je suis…", pt: "eu sou…" },
        { fr: "brésilien / brésilienne", pt: "brasileiro / brasileira" },
      ],
      grammar: {
        title: "Je m’appelle = eu me chamo",
        points: [
          "O francês usa je m’appelle X, não a estrutura “meu nome é”.",
          "Pergunta informal: Comment tu t’appelles ?",
          "Pergunta formal: Comment vous appelez-vous ?",
          "Enchanté (homem) / Enchantée (mulher).",
        ],
      },
      writing: {
        title: "Três frases sobre você",
        prompt: "Escreva: cumprimento + seu nome + uma linha Je suis… (nacionalidade).",
        example: "Bonjour. Je m’appelle Pedro. Je suis brésilien.",
      },
      quiz: [
        {
          id: "w1d2-q1",
          prompt: "Meu nome é… em francês:",
          options: ["Je suis…", "Je m’appelle…", "Ça va…", "Au revoir…"],
          correctIndex: 1,
        },
        {
          id: "w1d2-q2",
          prompt: "Como você se chama? (informal):",
          options: [
            "Comment vous appelez-vous ?",
            "Comment tu t’appelles ?",
            "Ça va ?",
            "Au revoir ?",
          ],
          correctIndex: 1,
        },
        {
          id: "w1d2-q3",
          prompt: "Prazer em conhecer (homem falando):",
          options: ["Enchantée", "Enchanté", "Merci", "Pardon"],
          correctIndex: 1,
        },
        {
          id: "w1d2-q4",
          prompt: "Eu sou brasileiro:",
          options: ["Je m’appelle brésilien", "Je suis brésilien", "Ça va brésilien", "Au revoir brésilien"],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "wed",
      label: "Quarta",
      title: "Merci, s’il vous plaît",
      focus: "Educação, sim e não",
      minutes: "~25–35 min de áudio + prática",
      lessonAudio: [
        pt("Quarta-feira. Hoje: palavras de educação. Essenciais em qualquer lugar."),
        pt("Oui significa sim."),
        fr("Oui."),
        pt("Non significa não."),
        fr("Non."),
        pt("S’il vous plaît significa por favor, no formal. Use em loja, café e trabalho."),
        fr("S’il vous plaît."),
        pt("Repita: s’il vous plaît."),
        fr("S’il vous plaît."),
        pt("S’il te plaît também é por favor, mas informal, com amigos."),
        fr("S’il te plaît."),
        pt("Merci beaucoup significa muito obrigado."),
        fr("Merci beaucoup."),
        pt("De rien significa de nada."),
        fr("De rien."),
        pt("Pardon significa perdão, ou com licença. Excusez-moi também é com licença, formal."),
        fr("Pardon."),
        fr("Excusez-moi."),
        pt("Un café significa um café."),
        fr("Un café."),
        pt("Frase completa para pedir: Un café, s’il vous plaît. Significa: um café, por favor."),
        fr("Un café, s’il vous plaît."),
        pt("Repita o pedido."),
        fr("Un café, s’il vous plaît."),
        pt("Cena no café. Ouça."),
        fr("Bonjour. Un café, s’il vous plaît."),
        fr("Oui."),
        fr("Merci beaucoup."),
        fr("De rien. Au revoir !"),
        pt("Tradução: oi, um café por favor; sim; muito obrigado; de nada, tchau."),
        pt("Fim da quarta. No Canadá e no TEF, o tom educado com vous ajuda bastante."),
      ],
      vocab: [
        { fr: "oui", pt: "sim" },
        { fr: "non", pt: "não" },
        { fr: "s’il vous plaît", pt: "por favor (formal)" },
        { fr: "s’il te plaît", pt: "por favor (informal)" },
        { fr: "merci beaucoup", pt: "muito obrigado" },
        { fr: "de rien", pt: "de nada" },
        { fr: "pardon", pt: "perdão / com licença" },
        { fr: "excusez-moi", pt: "com licença" },
        { fr: "un café", pt: "um café" },
      ],
      grammar: {
        title: "Por favor: te vs vous",
        points: [
          "s’il te plaît — amigos e família.",
          "s’il vous plaît — loja, trabalho, estranhos (padrão para imigração e TEF).",
          "De rien = de nada.",
        ],
      },
      writing: {
        title: "Pedido educado",
        prompt: "Escreva 3 linhas pedindo algo com educação e agradecendo.",
        example: "Bonjour. Un café, s’il vous plaît.\nMerci beaucoup.\nAu revoir !",
      },
      quiz: [
        {
          id: "w1d3-q1",
          prompt: "Por favor na loja:",
          options: ["S’il te plaît", "S’il vous plaît", "De rien", "Salut"],
          correctIndex: 1,
        },
        {
          id: "w1d3-q2",
          prompt: "De nada:",
          options: ["De rien", "Pardon", "Oui", "Non"],
          correctIndex: 0,
        },
        {
          id: "w1d3-q3",
          prompt: "Muito obrigado:",
          options: ["Merci beaucoup", "De rien", "Non", "Salut"],
          correctIndex: 0,
        },
        {
          id: "w1d3-q4",
          prompt: "Um café, por favor:",
          options: [
            "Un café, s’il te plaît (sempre)",
            "Un café, s’il vous plaît",
            "Café merci non",
            "Bonjour café toi",
          ],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "thu",
      label: "Quinta",
      title: "Zéro a dix",
      focus: "Números de 0 a 10",
      minutes: "~30–40 min de áudio + prática",
      lessonAudio: [
        pt("Quinta-feira. Números. Você vai precisar deles o tempo todo no TEF."),
        pt("Zéro é zero."),
        fr("Zéro."),
        pt("Un é um."),
        fr("Un."),
        pt("Deux é dois."),
        fr("Deux."),
        pt("Trois é três."),
        fr("Trois."),
        pt("Quatre é quatro."),
        fr("Quatre."),
        pt("Cinq é cinco."),
        fr("Cinq."),
        pt("Six é seis."),
        fr("Six."),
        pt("Sept é sete."),
        fr("Sept."),
        pt("Huit é oito."),
        fr("Huit."),
        pt("Neuf é nove."),
        fr("Neuf."),
        pt("Dix é dez."),
        fr("Dix."),
        pt("Agora conte de um a cinco sem pausa."),
        fr("Un, deux, trois, quatre, cinq."),
        pt("De seis a dez."),
        fr("Six, sept, huit, neuf, dix."),
        pt("Agora de trás para frente, de dez a seis."),
        fr("Dix, neuf, huit, sept, six."),
        pt("E de cinco a zero."),
        fr("Cinq, quatre, trois, deux, un, zéro."),
        pt("Ouça: deux et quatre. Significa dois e quatro."),
        fr("Deux et quatre."),
        pt("Repita a sequência completa de zero a dez."),
        fr("Zéro, un, deux, trois, quatre, cinq, six, sept, huit, neuf, dix."),
        pt("Fim da quinta. Treine contar no carro ou na academia sem olhar o texto."),
      ],
      vocab: [
        { fr: "zéro", pt: "0" },
        { fr: "un", pt: "1" },
        { fr: "deux", pt: "2" },
        { fr: "trois", pt: "3" },
        { fr: "quatre", pt: "4" },
        { fr: "cinq", pt: "5" },
        { fr: "six", pt: "6" },
        { fr: "sept", pt: "7" },
        { fr: "huit", pt: "8" },
        { fr: "neuf", pt: "9" },
        { fr: "dix", pt: "10" },
      ],
      grammar: {
        title: "Ouvir números",
        points: [
          "six e dix soam com s no final quando sozinhos: sees / dees.",
          "un é nasal — não é o “um” do português.",
          "Pratique subindo e descendo.",
        ],
      },
      writing: {
        title: "Escreva os números",
        prompt: "Escreva por extenso em francês: 0, 2, 5, 7, 10.",
        example: "zéro, deux, cinq, sept, dix",
      },
      quiz: [
        {
          id: "w1d4-q1",
          prompt: "huit =",
          options: ["6", "7", "8", "9"],
          correctIndex: 2,
        },
        {
          id: "w1d4-q2",
          prompt: "cinq =",
          options: ["4", "5", "6", "15"],
          correctIndex: 1,
        },
        {
          id: "w1d4-q3",
          prompt: "dix =",
          options: ["2", "6", "10", "12"],
          correctIndex: 2,
        },
        {
          id: "w1d4-q4",
          prompt: "trois =",
          options: ["2", "3", "4", "13"],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "fri",
      label: "Sexta",
      title: "Tudo junto",
      focus: "Conversa completa do dia a dia",
      minutes: "~30–40 min de áudio + prática",
      lessonAudio: [
        pt("Sexta-feira. Vamos juntar tudo que você aprendeu esta semana."),
        pt("Palavras novas rápidas. Un café, com ponto de interrogação, pode ser um oferecimento: quer um café?"),
        fr("Un café ?"),
        pt("D’accord significa ok, combinado."),
        fr("D’accord."),
        pt("Très bien significa muito bem."),
        fr("Très bien."),
        pt("À demain significa até amanhã."),
        fr("À demain."),
        pt("Agora a cena completa. Ouça com atenção."),
        fr("Bonjour !"),
        pt("Oi."),
        fr("Bonjour ! Ça va ?"),
        pt("Oi! Como vai?"),
        fr("Ça va bien, merci. Et vous ?"),
        pt("Estou bem, obrigado. E você?"),
        fr("Ça va. Je m’appelle Marie."),
        pt("Estou bem. Eu me chamo Marie."),
        fr("Enchanté. Je m’appelle Pedro."),
        pt("Prazer. Eu me chamo Pedro."),
        fr("Un café ?"),
        pt("Um café?"),
        fr("Oui. Un café, s’il vous plaît."),
        pt("Sim. Um café, por favor."),
        fr("Merci. Au revoir !"),
        pt("Obrigado. Tchau!"),
        fr("À bientôt !"),
        pt("Até logo!"),
        pt("Agora a cena outra vez, só em francês, para você memorizar o ritmo."),
        fr("Bonjour !"),
        fr("Bonjour ! Ça va ?"),
        fr("Ça va bien, merci. Et vous ?"),
        fr("Ça va. Je m’appelle Marie."),
        fr("Enchanté. Je m’appelle Pedro."),
        fr("Un café ?"),
        fr("Oui. Un café, s’il vous plaît."),
        fr("Merci. Au revoir !"),
        fr("À bientôt !"),
        pt("Fim da sexta. Tente gravar no celular falando o lado do Pedro."),
      ],
      vocab: [
        { fr: "un café ?", pt: "um café? (oferecendo)" },
        { fr: "d’accord", pt: "ok / combinado" },
        { fr: "très bien", pt: "muito bem" },
        { fr: "à demain", pt: "até amanhã" },
      ],
      grammar: {
        title: "Cola da conversa",
        points: [
          "Ordem: cumprimento → ça va → nomes → pedido educado → despedida.",
          "Frases curtas. Fluência vale mais que palavras difíceis no A0.",
          "Na semana dois entramos em rotina e je travaille.",
        ],
      },
      writing: {
        title: "Sua versão",
        prompt: "Reescreva o diálogo do café com o seu nome.",
        example:
          "Bonjour !\nÇa va ?\nÇa va bien, merci. Je m’appelle Pedro.\nUn café, s’il vous plaît.\nMerci. Au revoir !",
      },
      quiz: [
        {
          id: "w1d5-q1",
          prompt: "Melhor ordem num primeiro encontro:",
          options: [
            "Au revoir → Bonjour → Je m’appelle",
            "Bonjour → Ça va → Je m’appelle → Au revoir",
            "Dix → Merci → Non",
            "Café → Non → Salut",
          ],
          correctIndex: 1,
        },
        {
          id: "w1d5-q2",
          prompt: "À demain significa:",
          options: ["Até amanhã", "Até logo", "Boa noite", "Obrigado"],
          correctIndex: 0,
        },
        {
          id: "w1d5-q3",
          prompt: "D’accord significa:",
          options: ["De nada", "Ok / combinado", "Obrigado", "Não"],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "sat",
      label: "Sábado",
      title: "Bloco ativo — ensaio da prova",
      focus: "Produzir com tudo da semana (ensaio antes do domingo)",
      minutes: "~40–60 min",
      lessonAudio: [
        pt("Sábado. Dia de produzir. Amanhã é a prova da semana. Hoje é o ensaio."),
        pt("Aujourd’hui significa hoje."),
        fr("Aujourd’hui."),
        pt("Repita: aujourd’hui."),
        fr("Aujourd’hui."),
        pt("Demain significa amanhã."),
        fr("Demain."),
        pt("Repita: demain."),
        fr("Demain."),
        pt("Lire significa ler. Écrire significa escrever."),
        fr("Lire."),
        fr("Écrire."),
        pt("Ensaio um: apresentação completa."),
        fr("Bonjour. Je m’appelle Pedro. Ça va bien, merci. Et vous ?"),
        pt("Isso significa: oi, eu me chamo Pedro, estou bem, obrigado, e você?"),
        pt("Repita a apresentação."),
        fr("Bonjour. Je m’appelle Pedro. Ça va bien, merci. Et vous ?"),
        pt("Ensaio dois: pedido no café."),
        fr("Un café, s’il vous plaît. Merci beaucoup. De rien."),
        pt("Um café por favor. Muito obrigado. De nada."),
        pt("Repita o pedido."),
        fr("Un café, s’il vous plaît."),
        pt("Ensaio três: números de zero a dez."),
        fr("Zéro, un, deux, trois, quatre, cinq, six, sept, huit, neuf, dix."),
        pt("Ditado curto. Ouça e depois escreva na seção de escrita."),
        fr("Bonjour, je m’appelle Pedro."),
        fr("Ça va bien, merci."),
        fr("Un café, s’il vous plaît."),
        fr("Au revoir. À demain."),
        pt("Checkpoint falado: grave sessenta segundos só em francês com cumprimento, nome, ça va, um número e despedida."),
        pt("Fim do ensaio de sábado. Faça a escrita e o quiz. Amanhã: prova completa da semana um."),
      ],
      vocab: [
        { fr: "aujourd’hui", pt: "hoje" },
        { fr: "demain", pt: "amanhã" },
        { fr: "lire", pt: "ler" },
        { fr: "écrire", pt: "escrever" },
        { fr: "réviser", pt: "revisar" },
      ],
      grammar: {
        title: "Ensaio antes da prova",
        points: [
          "Sábado = produzir, não só consumir.",
          "Escreva frases completas. Confira acentos: é è à ù ç.",
          "Leia em voz alta depois de escrever.",
          "Amanhã a prova cobre cumprimentos, nome, educação, números e diálogo.",
        ],
      },
      writing: {
        title: "Ensaio escrito (cena completa)",
        prompt:
          "Escreva uma cena em Calgary: encontro no trabalho, nomes, ça va, peça um café com educação, conte até três, se despeça. Só francês.",
        example:
          "Bonjour !\nJe m’appelle Pedro. Et vous ?\nÇa va bien, merci.\nUn café, s’il vous plaît.\nUn, deux, trois.\nMerci beaucoup.\nAu revoir ! À demain !",
      },
      quiz: [
        {
          id: "w1d6-q1",
          prompt: "Forma correta:",
          options: ["je mappelle", "je m’appelle", "je mapelle", "j’mapel"],
          correctIndex: 1,
        },
        {
          id: "w1d6-q2",
          prompt: "Por favor formal:",
          options: ["s’il vous plaît", "sil vou ple", "si vous play", "s’il te merci"],
          correctIndex: 0,
        },
        {
          id: "w1d6-q3",
          prompt: "Aujourd’hui significa:",
          options: ["Ontem", "Hoje", "Amanhã", "Sempre"],
          correctIndex: 1,
        },
        {
          id: "w1d6-q4",
          prompt: "sept =",
          options: ["6", "7", "8", "17"],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "sun",
      label: "Domingo",
      title: "Prova da semana 1",
      focus: "Resumo total: áudio de tudo + quiz + escrita (como prova)",
      minutes: "~45–70 min",
      lessonAudio: [
        pt("Domingo. Hoje é a prova da semana um. Ouça o resumo completo, depois faça o quiz e a escrita sem olhar o gabarito primeiro."),
        pt("Parte um: cumprimentos. Bonjour significa oi ou bom dia."),
        fr("Bonjour."),
        pt("Salut é oi informal."),
        fr("Salut."),
        pt("Bonsoir é boa noite."),
        fr("Bonsoir."),
        pt("Au revoir é tchau educado."),
        fr("Au revoir."),
        pt("À bientôt é até logo."),
        fr("À bientôt."),
        pt("À demain é até amanhã."),
        fr("À demain."),
        pt("Ça va pergunta como vai. Ça va bien responde estou bem. Merci é obrigado."),
        fr("Ça va ?"),
        fr("Ça va bien, merci."),
        pt("Et toi é e você informal. Et vous é e você formal."),
        fr("Et toi ?"),
        fr("Et vous ?"),
        pt("Parte dois: nome. Je m’appelle significa eu me chamo."),
        fr("Je m’appelle Pedro."),
        pt("Comment tu t’appelles é como você se chama, informal."),
        fr("Comment tu t’appelles ?"),
        pt("Comment vous appelez-vous é a forma formal."),
        fr("Comment vous appelez-vous ?"),
        pt("Enchanté ou enchantée significa prazer em conhecer."),
        fr("Enchanté."),
        fr("Enchantée."),
        pt("Je suis brésilien significa eu sou brasileiro."),
        fr("Je suis brésilien."),
        pt("Parte três: educação. Oui é sim. Non é não."),
        fr("Oui."),
        fr("Non."),
        pt("S’il vous plaît é por favor formal. Merci beaucoup é muito obrigado. De rien é de nada."),
        fr("S’il vous plaît."),
        fr("Merci beaucoup."),
        fr("De rien."),
        pt("Un café, s’il vous plaît significa um café, por favor."),
        fr("Un café, s’il vous plaît."),
        pt("Parte quatro: números de zero a dez."),
        fr("Zéro."),
        fr("Un."),
        fr("Deux."),
        fr("Trois."),
        fr("Quatre."),
        fr("Cinq."),
        fr("Six."),
        fr("Sept."),
        fr("Huit."),
        fr("Neuf."),
        fr("Dix."),
        pt("Conte junto, de zero a dez."),
        fr("Zéro, un, deux, trois, quatre, cinq, six, sept, huit, neuf, dix."),
        pt("Parte cinco: diálogo completo da prova. Ouça só em francês."),
        fr("Bonjour !"),
        fr("Bonjour ! Ça va ?"),
        fr("Ça va bien, merci. Et vous ?"),
        fr("Ça va. Je m’appelle Marie. Et vous ?"),
        fr("Je m’appelle Pedro. Enchanté."),
        fr("Un café ?"),
        fr("Oui. Un café, s’il vous plaît."),
        fr("Merci beaucoup."),
        fr("De rien. Au revoir !"),
        fr("À demain !"),
        pt("Tradução rápida: oi; oi, como vai; bem, obrigado, e você; bem, eu me chamo Marie; eu me chamo Pedro, prazer; um café; sim, um café por favor; muito obrigado; de nada, tchau; até amanhã."),
        pt("Ouça o diálogo mais uma vez, só francês, como no exame."),
        fr("Bonjour ! Ça va ?"),
        fr("Ça va bien, merci. Je m’appelle Pedro."),
        fr("Un café, s’il vous plaît."),
        fr("Merci. Au revoir. À bientôt."),
        pt("Fim do áudio da prova. Agora faça o quiz completo e a escrita da prova. Semana dois começa depois que você concluir domingo."),
      ],
      vocab: [
        { fr: "bonjour", pt: "oi / bom dia" },
        { fr: "salut", pt: "oi / tchau informal" },
        { fr: "bonsoir", pt: "boa noite" },
        { fr: "au revoir", pt: "tchau" },
        { fr: "à bientôt", pt: "até logo" },
        { fr: "à demain", pt: "até amanhã" },
        { fr: "ça va ?", pt: "como vai?" },
        { fr: "ça va bien", pt: "estou bem" },
        { fr: "merci", pt: "obrigado" },
        { fr: "merci beaucoup", pt: "muito obrigado" },
        { fr: "et toi ?", pt: "e você? informal" },
        { fr: "et vous ?", pt: "e você? formal" },
        { fr: "je m’appelle", pt: "eu me chamo" },
        { fr: "comment tu t’appelles ?", pt: "como você se chama? informal" },
        { fr: "comment vous appelez-vous ?", pt: "como você se chama? formal" },
        { fr: "enchanté / enchantée", pt: "prazer em conhecer" },
        { fr: "je suis brésilien", pt: "eu sou brasileiro" },
        { fr: "oui", pt: "sim" },
        { fr: "non", pt: "não" },
        { fr: "s’il vous plaît", pt: "por favor formal" },
        { fr: "de rien", pt: "de nada" },
        { fr: "un café", pt: "um café" },
        { fr: "d’accord", pt: "ok / combinado" },
        { fr: "aujourd’hui", pt: "hoje" },
        { fr: "demain", pt: "amanhã" },
        { fr: "zéro", pt: "0" },
        { fr: "un", pt: "1" },
        { fr: "deux", pt: "2" },
        { fr: "trois", pt: "3" },
        { fr: "quatre", pt: "4" },
        { fr: "cinq", pt: "5" },
        { fr: "six", pt: "6" },
        { fr: "sept", pt: "7" },
        { fr: "huit", pt: "8" },
        { fr: "neuf", pt: "9" },
        { fr: "dix", pt: "10" },
      ],
      grammar: {
        title: "Prova — gramática da semana 1",
        points: [
          "Tu e toi são informais; vous é formal ou plural — no trabalho prefira vous.",
          "Je m’appelle X = eu me chamo X. Não diga meu nome é com a estrutura do português.",
          "S’il vous plaît na loja e no trabalho; s’il te plaît com amigos.",
          "Ordem do diálogo: cumprimento, ça va, nomes, pedido educado, despedida.",
          "Números: treine subir e descer; six e dix terminam com som de s.",
        ],
      },
      writing: {
        title: "Prova escrita",
        prompt:
          "PROVA — responda em francês (pode usar o roteiro só depois para corrigir):\n1) Diálogo de 8–12 linhas: encontro no trabalho em Calgary (cumprimento, ça va, nomes, café, número de um a cinco, despedida).\n2) Escreva por extenso: 0, 3, 7, 10.\n3) Uma frase com je m’appelle e uma com s’il vous plaît.",
        example:
          "1)\nBonjour !\nÇa va ?\nÇa va bien, merci. Je m’appelle Pedro. Et vous ?\nJe m’appelle Marie.\nUn café, s’il vous plaît.\nUn, deux, trois.\nMerci beaucoup.\nAu revoir ! À demain !\n\n2) zéro, trois, sept, dix\n\n3) Je m’appelle Pedro. Un café, s’il vous plaît.",
      },
      quiz: [
        {
          id: "w1exam-q1",
          prompt: "Cumprimento educado de dia:",
          options: ["Salut", "Bonjour", "À demain", "Non"],
          correctIndex: 1,
        },
        {
          id: "w1exam-q2",
          prompt: "Como vai?",
          options: ["Ça va ?", "Au revoir", "Dix", "Lire"],
          correctIndex: 0,
        },
        {
          id: "w1exam-q3",
          prompt: "Eu me chamo Pedro:",
          options: ["Je suis Pedro", "Je m’appelle Pedro", "Comment Pedro", "Merci Pedro"],
          correctIndex: 1,
        },
        {
          id: "w1exam-q4",
          prompt: "Como você se chama? (formal):",
          options: [
            "Comment tu t’appelles ?",
            "Comment vous appelez-vous ?",
            "Ça va vous ?",
            "Bonsoir vous ?",
          ],
          correctIndex: 1,
        },
        {
          id: "w1exam-q5",
          prompt: "Por favor no café / trabalho:",
          options: ["S’il te plaît", "S’il vous plaît", "De rien", "Salut"],
          correctIndex: 1,
        },
        {
          id: "w1exam-q6",
          prompt: "De nada:",
          options: ["De rien", "Merci beaucoup", "Pardon", "Oui"],
          correctIndex: 0,
        },
        {
          id: "w1exam-q7",
          prompt: "huit =",
          options: ["6", "7", "8", "9"],
          correctIndex: 2,
        },
        {
          id: "w1exam-q8",
          prompt: "cinq =",
          options: ["4", "5", "15", "50"],
          correctIndex: 1,
        },
        {
          id: "w1exam-q9",
          prompt: "À demain =",
          options: ["Até logo", "Até amanhã", "Boa noite", "Obrigado"],
          correctIndex: 1,
        },
        {
          id: "w1exam-q10",
          prompt: "Melhor ordem do diálogo:",
          options: [
            "Au revoir → café → Bonjour",
            "Bonjour → Ça va → nome → café → Au revoir",
            "Dix → Non → Salut",
            "Merci → Non → Bonsoir só",
          ],
          correctIndex: 1,
        },
        {
          id: "w1exam-q11",
          prompt: "No trabalho, “e você?”:",
          options: ["Et toi ?", "Et vous ?", "Et moi ?", "Et café ?"],
          correctIndex: 1,
        },
        {
          id: "w1exam-q12",
          prompt: "Você passou na prova oral da semana se consegue:",
          options: [
            "Só ler em silêncio",
            "Fazer ~60 segundos de diálogo sem português",
            "Pular o áudio",
            "Usar só inglês",
          ],
          correctIndex: 1,
        },
      ],
    },
  ],
};
